[package]
name = "akari"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.23.0"
vizia = { git = "https://github.com/DasLixou/vizia", branch = "bump-femtovg" }

[patch.crates-io]
femtovg = { git = "https://github.com/DasLixou/femtovg", branch = "const-paint" }