[package]
name = "akari"
version = "0.1.0"
edition = "2021"
include = ["/src", "/README.md"]

[dependencies]
akari_logger = { path = "crates/akari_logger" }
akari_ui = { path = "crates/akari_ui" }

[workspace]
members = ["crates/*"]
